### PR TITLE
Add EGL and wDGLD

### PR DESCRIPTION
**Pull request by EndymionJkb**
We have a wDGLD pool with $125k, and EGL's in $70m

### CODE REVIEW

**Comment by EndymionJkb** [comment]
Updated to latest master. 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0 is in both listed.json and ui-not-eligible.json?

**Comment by garethfuller** [comment]
@EndymionJkb am I the right person to approve this? I've never really approved assets repo PRs before.

**Comment by EndymionJkb** [comment]
> @EndymionJkb am I the right person to approve this? I've never really approved assets repo PRs before.

Ok; maybe Rab then.

**Comment by rabmarut** [comment]
Replaced by #367

**Pull request closed without merging**
